### ISSUE TITLE
Error operation.rb

### ISSUE THREAD

**Issue by danubiapaiva** [LessPainful/calabash-ios#1]
Please, 

Has anyone seen this error?

RuntimeError: Could not execute command to start test server
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/calabash-android-0.9.0/lib/calabash-android/operations.rb:734:in `start_test_server_in_background'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/calabash-android-0.9.0/lib/calabash-android/operations.rb:152:in `start_test_server_in_background'
        from (irb):2
        from C:/Ruby23/bin/irb.cmd:19:in `<main>'

**Comment by danubiapaiva** [comment]
The error occurs while executing the command "start_test_server_in_background", does not open the application. The lines that have errors are in operation.rb that call the command I execute.

I'm working with ruby23, windows10
